[profile.default]
solc_version = "0.8.17"
optimizer = true
optimizer_runs = 200

src = "contracts"
out = "build"
test = "forge-test"

libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@solidity-parser/=node_modules/@solidity-parser/",
    "ds-test/=lib/forge-std/lib/ds-test/src/",
    "forge-std/=lib/forge-std/src/",
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
