apiVersion: apps/v1
kind: Deployment
metadata:
  name:  simple-gr
  namespace: generic-relayer
  labels:
    app:  simple-gr
spec:
  selector:
    matchLabels:
      app: simple-gr
  replicas: 1
  template:
    metadata:
      namespace: generic-relayer
      labels:
        app:  simple-gr
    spec:
      restartPolicy: Always
      containers:
      - name:  simple-gr
        image:  ghcr.io/wormhole-foundation/trustless-generic-relayer:main
        imagePullPolicy: Always
        # uncomment to explore filesystem during crash loop
        # command: [ "/bin/sh", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
        resources:
          requests:
#            cpu: 500m
            memory: 600Mi
          limits:
            cpu: 800m
            memory: 2000Mi
        volumeMounts:
        - name: relayer-contracts
          mountPath: /usr/src/ethereum/ts-scripts/config/k8s-testnet
        - name: relayer-engine-config
          mountPath: /usr/src/app/engine_config/k8s-testnet
        - name: generic-relayer-plugin-config
          mountPath: /usr/src/app/src/plugin/config
        env:
        - name: PRIVATE_KEYS_CHAIN_4
          valueFrom:
            secretKeyRef:
              name: private-keys
              key: PRIVATE_KEYS_CHAIN_4
              optional: false
        - name: PRIVATE_KEYS_CHAIN_5
          valueFrom:
            secretKeyRef:
              name: private-keys
              key: PRIVATE_KEYS_CHAIN_5
              optional: false
        - name: PRIVATE_KEYS_CHAIN_6
          valueFrom:
            secretKeyRef:
              name: private-keys
              key: PRIVATE_KEYS_CHAIN_6
              optional: false
        - name: PRIVATE_KEYS_CHAIN_14
          valueFrom:
            secretKeyRef:
              name: private-keys
              key: PRIVATE_KEYS_CHAIN_14
              optional: false
        - name: PRIVATE_KEYS_CHAIN_16
          valueFrom:
            secretKeyRef:
              name: private-keys
              key: PRIVATE_KEYS_CHAIN_16
              optional: false
        envFrom:
          - secretRef:
              name: redis-generic-relayer
      volumes:
        - name: relayer-contracts
          configMap:
            name: relayer-contracts
        - name: relayer-engine-config
          configMap:
            name: relayer-engine-config
        - name: generic-relayer-plugin-config
          configMap:
            name: generic-relayer-plugin-config
