apiVersion: apps/v1
kind: Deployment
metadata:
  name:  simple-gr
  namespace: default
  labels:
    app:  simple-gr
spec:
  selector:
    matchLabels:
      app: simple-gr
  replicas: 1
  template:
    metadata:
      labels:
        app:  simple-gr
    spec:
      restartPolicy: Always 
      containers:
      - name:  simple-gr
        image:  joehowarth/simple-gr:latest
        imagePullPolicy: IfNotPresent
        # command: [ "/bin/sh", "-c", "--" ]
        # args: [ "while true; do sleep 30; done;" ]
        resources:
          requests:
            cpu: 1
            memory: 100Mi
          limits:
            cpu: 2
            memory: 2000Mi
        volumeMounts:
        - name: relayer-engine-config
          mountPath: /usr/src/app/engine_config/k8s-testnet
        - name: generic-relayer-plugin-config
          mountPath: /usr/src/app/src/plugin/config
        env:
        - name: PRIVATE_KEYS_CHAIN_14 
          valueFrom:
            secretKeyRef:
              name: private-keys
              key: PRIVATE_KEYS_CHAIN_14
              optional: false 
        - name: PRIVATE_KEYS_CHAIN_6
          valueFrom:
            secretKeyRef:
              name: private-keys
              key: PRIVATE_KEYS_CHAIN_6
              optional: false 
      volumes:
        - name: relayer-engine-config
          configMap:
            name: relayer-engine-config
        - name: generic-relayer-plugin-config
          configMap:
            name: generic-relayer-plugin-config
